### ISSUE TITLE
Error on new order

### ISSUE THREAD

**Issue by Sageboba** [djmango/BlackMarket2#65]
Playing with Py's mods. I get an error when pressing new order on a buy chest.
![image](https://github.com/user-attachments/assets/17e5293c-6c91-476b-a5d8-984e1608c0ba)

**Comment by djmango** [comment]
@tno1 @LoganDark could this be caused by an overwrite of coal?

**Comment by LoganDark** [comment]
> @tno1 @LoganDark could this be caused by an overwrite of coal?

probably. not sure why BM2 doesn't use ucoin here

**Comment by tno1** [comment]
Could be djmango, but idk what it could be specific about coal thats blocked, and as Logan said, should use ucoin instead of coal just incase something changes the item "coal". 

I can't run py with space age enabled, but with non space age dlc, then it runs fine without any issues, would be great if you could tell us which mods your running, since it might be something else thats changing the coal

**Comment by Sageboba** [comment]
Sure, here's my mod-list.json if it's any help.
[mod-list.json](https://github.com/user-attachments/files/17684701/mod-list.json)

**Comment by LoganDark** [comment]
> idk what it could be specific about coal thats blocked

`storage.prices.coal.current` is failing because `storage.prices.coal` doesn't exist, which can only happen in 2 cases:

1. prices not calculated yet (not possible because it definitely happens before the user has a chance to click new order)
2. coal does not exist (item/recipe/etc was removed by mod?)

I'm betting on 2 since mods *can* remove items.

**Comment by tno1** [comment]
> Sure, here's my mod-list.json if it's any help. [mod-list.json](https://github.com/user-attachments/files/17684701/mod-list.json)

Uhm, can you tell me the exact steps you'r taking? since I just downloaded all those mods, as if I just fresh installed all of it, nothing breaks, I can as 0 research, 0 everything except 1 buy chest, and I can add new orders, remove orders and create again, buy & sell. 

So so by that idk what's going on, but any case a change from: 
"
table.insert(trader.orders,1,{name="coal", count=0, price=storage.prices.coal.current, quality=1})
"

to

"
table.insert(trader.orders,1,{name="ucoin", count=0, price=storage.prices.coal.current, quality=1})
"

should do the trick

**Comment by Sageboba** [comment]
> Uhm, can you tell me the exact steps you'r taking? since I just downloaded all those mods, as if I just fresh installed all of it, nothing breaks, I can as 0 research, 0 everything except 1 buy chest, and I can add new orders, remove orders and create again, buy & sell.

I just put down a buy chest, press new order and immediately get that error. Come to think of it, I'm not sure that it was happening when I started my save at first, but after playing for a bit it happens every time now without fail.

**Comment by LoganDark** [comment]
if you don't mind losing achievements, try this console command:

`/c remote.call( "market", "prices" )`

this should recalculate all prices and then you can see if coal exists again

**Comment by Sageboba** [comment]
Just tried it, and I still get the same error even if I use that command.

**Comment by tno1** [comment]
After you created the map/save, have you updated any mods? 

Did you just finish a research? if you did, which research

Was the buy chest placed manually, by bot or by some sort of 3rd party script/mod

Which version of Factorio are you playing on? (shouldn't have anything to do with it, but grasping at straws)

Can you share the save map? 

Sorry for all the questions, but when I can't really recreate the error then its a bit of a guesswork.

**Comment by Sageboba** [comment]
I'm pretty sure I've updated most of Py's mod suite after starting the save.

Not sure about the research.

Buy chests have all been placed manually.

2.0.15 (Which I believe is latest)

And here's the save.
[Black Market 2 New Order Error.zip](https://github.com/user-attachments/files/17685587/Black.Market.2.New.Order.Error.zip)

**Comment by tno1** [comment]
Okay found one issue, it's removing the coal before load, and something has ensured that it was not created on launch. 

But found a fix, which is just changing it from coal to ucoin, that works, will make a Pull Request

**Comment by djmango** [comment]
Thx @tno1  and @Sageboba and @LoganDark !!
